set nocompatible
syntax on
set number
set relativenumber
set encoding=utf-8
set wrap
set showmatch

set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set expandtab
set smartindent

set ignorecase
set hlsearch
set incsearch
set smartcase

set nolist
set scrolloff=7
set ruler
set noswapfile
set clipboard=unnamedplus
set laststatus=2
